dataset_folder: /project/trinity/datasets/apricot/pub/apricot-mask/dev/data_mask_v2/
batch_size: 2
num_images: 4
img_shape: (512,512)
sam_model_path: /project/trinity/pretrained_models/sam_facebook/sam_vit_h_4b8939.pth
use_gpu: True
maximum_segments: 20
visualize: True
normalizing_algo: None
use_fft: True
use_dct: True
use_entropy: False