# dataset_folder: /project/trinity/datasets/apricot/pub/apricot-mask/dev/data_mask_v2/
dataset_folder: /project/trinity/datasets/apricot/pub/apricot-mask/data_mask_v2/
batch_size: 32
num_images:
img_shape: (512,512)
scale: 1.0
sam_model_path: /project/trinity/pretrained_models/sam_facebook/sam_vit_h_4b8939.pth
use_gpu: True
maximum_segments: 40
visualize: True
normalizing_algo: None
use_fft: False
use_dct: True
use_entropy: False
use_grayscale: True
use_3d: False
# feature_save_folder: /project/trinity/datasets/apricot_features/dev/
feature_save_folder: /project/trinity/datasets/apricot_features/test/